### PR TITLE
added field to register

### LINKED ISSUE #3: Add role field to each user (instructor, student, TA)

### LINKED ISSUE #4: Create interface to select role for users that don't have a role

### PR DESCRIPTION
**Pull request by sa2415**
resolves https://github.com/CMU-313/fall23-nodebb-consonants-compadres/issues/3 and resolves #4 
During the registration, a new dropdown has been added

### CODE REVIEW

**Review by lwei11 — APPROVED** [review]

**Comment by phyllis-feng** [comment]
Good progress!

**Review by lwei11 — APPROVED** [review]
well done!

**Review by phyllis-feng — APPROVED** [review]
Approved!

**Review by monicaq21 — APPROVED** [review]
nice!

**Pull request merged**
